### ISSUE TITLE
Mage not auto-equipping casting gear

### ISSUE THREAD

**Issue by Phildo85** [atperry7/pup_gearswap#10]
The situation is master and mage DD engaged.  With the prediction, it correctly sets Master mode when I am engaged with mage pup. I only have an elemental spell set listed in the lua. When I engage, chat log message says that I am in Master only mode and has the correct master tp gear set, and it correctly swaps to my WS gear also when WSing.  The problem is it does not swap to pet mage gear when using elemental spells. I tried copying that elemental spell set into the top set for the base mage casting gear and it then did change to the mage gear when it casted, but then never changed back to my tp gear when finished. I've not tested it with only pet engaged, but that's not a huge deal as I can just stay in elemental gear the whole time in that case.

**Comment by atperry7** [comment]
Curious, the Hybrid Mode was set to TP? Sounds like it set the OffenseMode to Master. Seems like an interesting bug if it's not correctly changing back. Of course, it is usually best to make sure all sets are filled in even.

**Comment by Phildo85** [comment]
Whenever the pup is recognized as Mage DD, as soon as I engage, it auto sets itself to Master only, even after I deploy the pup.  Since it is recognized as master only, it is not swapping to casting gear. 
I tried to remedy this by making the Hybrid Regen set the same as my Master only tp gear so that I could engage, then change to MasterPet, and then scroll to HybridRegen.  The problem with that  was that every time I engaged the next mob, it automatically set it back to Master only, and when I hit the keybind to change it to MasterPet again, I had to scroll through the whole Hybrid list to get it back to HybridRegen (It would not automatically change to MasterPet when  I deployed Mage pup)

Is there some  way to keep it  from automatically choosing switching  me to Master Only mode (with Mage DD) when I engage a new mob?

**Comment by atperry7** [comment]
Yes, that is possible.

Within the TotalSCalc() you would want to remove this line:

**handle_set({"OffenseMode", "Master"})**

(Edit: Could potentially set that to **handle_set({"OffenseMode", "MasterPet"})** , then it would default to the MasterPet for OffenseMode).

That function is what determines the "State" that a Player and the Pet is in based on PetMode then whether or not they are engaged or idle.

**Comment by atperry7** [comment]
Closing for now. Welcome to reopen/create one if more assistance is needed.
