### ISSUE TITLE
nil variable 'modif'

### ISSUE THREAD

**Issue by Icydeath** [atperry7/pup_gearswap#8]
Gearswap throws a nil variable error on modif in function job_aftercast.
`add_to_chat(392,"*-*-*-*-*-*-*-*-* [ " .. pet.name .. " is about to " .. ws .. " (" .. modif .. ") ] *-*-*-*-*-*-*-*-*")`

As a quick fix so I don't see the error anymore, I wrapped it in a nil check.

`if modif ~= nil then`
  `add_to_chat(392,"*-*-*-*-*-*-*-*-* [ " .. pet.name .. " is about to " .. ws .. " (" .. modif .. ") ] *-*-*-*-*-*-*-*-*")`
`end`

**Comment by atperry7** [comment]
Good find. I updated that section to now also default to a standard Weapon Skill set if it is unable to find the modif Weapon Skill set as well.

New update I just pushed also includes a lock timer for the pet weapon skill gear too. 👍

**Comment by Icydeath** [comment]
Awesome! Keep up the good work sir!
