### ISSUE TITLE
nil error on pet.tp in event prerender

### ISSUE THREAD

**Issue by Icydeath** [atperry7/pup_gearswap#9]
When I was swapping out my pup the following threw a nil error on pet.tp and caused .lua to not function properly anymore.

Even though there is some good checks in place like pet.isvalid it seems that it might squeak by it at times. Below is my attempt to prevent the nil error...

In event
```
windower.register_event(
    "prerender",
```
I simply wrapped the conditions in a not equal nil to help prevent the issue: 
```
if pet.isvalid and player.hpp > 0 then
  ...
 if pet.tp ~= nil  -- Sanity check
    if pet.tp >= 1000 and petWeaponSkillRecast <= 0 and startedPetWeaponSkillTimer == true then
      ...
    end
  end
end
```
and
```
if pet.isvalid and (state.PetStyleCycle.value:lower() == "spam" or state.PetStyleCycle.value:lower() == "dd") and Master_State:lower() == "idle" then
  if pet.tp ~= nil then -- Sanity check
    ...
  end
end
```

Even with those sanity checks I'm thinking this may crop up from time to time.

**Comment by atperry7** [comment]
That is interesting. What puppet were you using? I wonder if we can dig a little deeper behind that. Could have been a dropped packet behind the scenes that may have caused it as well, but wouldn't hurt to have a check similar to that for sure.
